// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwhxtcnjmdfzmyadisfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3aHh0Y25qbWRmem15YWRpc2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5OTY0ODMsImV4cCI6MjA5MDU3MjQ4M30.orD9TWLW3zy2uJsFPpC1ugzV2kKLs_WhUZW3ARa-v2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
